---
apiVersion: v1
kind: Template
metadata:
  name: pipeline-run-template
  annotations:
    description: "Description"
objects:
- apiVersion: tekton.dev/v1beta1
  kind: PipelineRun
  metadata:
    generateName: catapp-build-and-deploy-
    namespace: ${NAMESPACE}
  spec:
    serviceAccountName: tekton-triggers-sa
    pipelineRef:
      name: build-and-deploy-openshift
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: revision
          value: ${GITREVISION}
        - name: url
          value: ${GITURL}
    - name: image
      resourceSpec:
        type: image
        params:
        - name: url
          value: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/catapp:${REVISION}
    params:
    - name: DEPLOYMENT
      value: ${DEPLOYMENT}
parameters:
- description: OCP Namespace
  name: NAMESPACE
- description: Git branch
  name: GITREVISION
- description: Git URL
  name: GITURL
- description: Git URL
  name: DEPLOYMENT
# - apiVersion: tekton.dev/v1beta1
#   kind: PipelineRun
#   metadata:
#     generateName: pipeline-run-
#     namespace: ${NAMESPACE}
#   spec:
#     serviceAccountName: tekton-triggers-sa
#     pipelineRef:
#       name: echo-pipeline
#     resources:
#       - name: source-repo
#         resourceSpec:
#           type: git
#           params:
#           - name: revision
#             value: ${GITREVISION}
#           - name: url
#             value: ${GITURL}
# parameters:
# - description: OCP Namespace
#   name: NAMESPACE
# - description: Git branch
#   name: GITREVISION
# - description: Git URL
#   name: GITURL